import { Incident, AreaIntelligence, CommunityStats } from '@/src/types';
import { CALGARY_CENTER } from '@/src/constants';

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: '1',
    title: 'Suspicious Activity in Beltline',
    description: 'Two individuals seen attempting to open car doors along 12th Ave SW. Reported to police.',
    category: 'crime',
    neighborhood: 'Beltline',
    lat: 51.0411,
    lng: -114.0719,
    timestamp: Date.now() - 1000 * 60 * 45, // 45 mins ago
    email: 'user1@example.com',
    name: 'Alex R.',
    verified_status: 'multiple_reports',
    report_count: 3,
    source_name: 'Community Report',
    source_logo: 'https://picsum.photos/seed/community/100/100',
  },
  {
    id: '2',
    title: 'Major Accident on Deerfoot Trail',
    description: 'Three-car collision near Memorial Drive. Traffic is backed up for several kilometers. Emergency services on scene.',
    category: 'traffic',
    neighborhood: 'Downtown',
    lat: 51.0501,
    lng: -114.0189,
    timestamp: Date.now() - 1000 * 60 * 120, // 2 hours ago
    email: 'user2@example.com',
    name: 'Sarah M.',
    verified_status: 'community_confirmed',
    report_count: 12,
    source_name: 'Calgary Police Service',
    source_url: 'https://www.calgary.ca/cps.html',
    source_logo: 'https://www.calgary.ca/content/dam/www/cps/images/cps-logo.png',
  },
  {
    id: '3',
    title: 'Water Main Break in Kensington',
    description: 'Significant flooding on the street in Kensington. City crews are on site working on repairs.',
    category: 'infrastructure',
    neighborhood: 'Kensington',
    lat: 51.0521,
    lng: -114.0859,
    timestamp: Date.now() - 1000 * 60 * 30, // 30 mins ago
    email: 'user3@example.com',
    name: 'David L.',
    verified_status: 'community_confirmed',
    report_count: 1,
    source_name: 'City of Calgary',
    source_url: 'https://www.calgary.ca/water/projects/water-main-breaks.html',
    source_logo: 'https://www.calgary.ca/content/dam/www/general/images/city-of-calgary-logo.png',
  },
  {
    id: '4',
    title: 'Severe Hail Warning - NW',
    description: 'Large hail reported in the NW. Residents advised to stay indoors and protect property. Storm moving east.',
    category: 'weather',
    neighborhood: 'Bowness',
    lat: 51.1261,
    lng: -114.1559,
    timestamp: Date.now() - 1000 * 60 * 15, // 15 mins ago
    email: 'user4@example.com',
    name: 'Emma W.',
    verified_status: 'multiple_reports',
    report_count: 8,
    source_name: 'Environment Canada',
    source_url: 'https://weather.gc.ca/city/pages/ab-52_metric_e.html',
    source_logo: 'https://www.canada.ca/etc/designs/canada/wet-boew/assets/sig-blk-en.svg',
  },
  {
    id: '5',
    title: 'Power Outage in Bridgeland',
    description: 'Widespread power outage affecting several blocks in Bridgeland. ENMAX is investigating the cause.',
    category: 'infrastructure',
    neighborhood: 'Bridgeland',
    lat: 51.0531,
    lng: -114.0419,
    timestamp: Date.now() - 1000 * 60 * 60, // 1 hour ago
    email: 'user5@example.com',
    name: 'Michael B.',
    verified_status: 'multiple_reports',
    report_count: 5,
    source_name: 'ENMAX Power',
    source_url: 'https://www.enmax.com/outages',
    source_logo: 'https://www.enmax.com/content/dam/enmax/logos/enmax-logo.svg',
  },
  {
    id: '6',
    title: 'Theft from Vehicle in Mission',
    description: 'Window smashed and laptop stolen from a parked car near 4th St SW. Police file #24-12345.',
    category: 'crime',
    neighborhood: 'Mission',
    lat: 51.0331,
    lng: -114.0719,
    timestamp: Date.now() - 1000 * 60 * 90, // 1.5 hours ago
    email: 'user6@example.com',
    name: 'Jessica K.',
    verified_status: 'unverified',
    report_count: 1,
    source_name: 'Community Report',
    source_logo: 'https://picsum.photos/seed/community2/100/100',
  },
  {
    id: '7',
    title: 'Road Closure in Inglewood',
    description: '9th Ave SE closed for emergency utility repairs. Use alternative routes. Expected reopening tomorrow.',
    category: 'traffic',
    neighborhood: 'Inglewood',
    lat: 51.0421,
    lng: -114.0359,
    timestamp: Date.now() - 1000 * 60 * 10, // 10 mins ago
    email: 'user7@example.com',
    name: 'Robert T.',
    verified_status: 'community_confirmed',
    report_count: 4,
    source_name: 'City of Calgary Transportation',
    source_url: 'https://www.calgary.ca/transportation/road-closures.html',
    source_logo: 'https://www.calgary.ca/content/dam/www/general/images/city-of-calgary-logo.png',
  },
  {
    id: '8',
    title: 'Fallen Tree in Bowness',
    description: 'Large tree branch blocking a residential street in Bowness following high winds. 311 ticket submitted.',
    category: 'infrastructure',
    neighborhood: 'Bowness',
    lat: 51.0921,
    lng: -114.2059,
    timestamp: Date.now() - 1000 * 60 * 240, // 4 hours ago
    email: 'user8@example.com',
    name: 'Linda P.',
    verified_status: 'multiple_reports',
    report_count: 2,
    source_name: '311 Calgary',
    source_url: 'https://www.calgary.ca/311.html',
    source_logo: 'https://www.calgary.ca/content/dam/www/general/images/city-of-calgary-logo.png',
  },
  {
    id: 'gas-1',
    title: 'Gas Price: $1.78/L at Costco',
    description: 'Costco Wholesale (Deerfoot City) reporting $1.78/L for regular. Lineups are moderate.',
    category: 'gas',
    neighborhood: 'Northeast',
    lat: 51.107,
    lng: -114.043,
    timestamp: Date.now() - 1000 * 60 * 10, // 10 mins ago
    email: 'gas_watcher@example.com',
    name: 'GasWatcher YYC',
    verified_status: 'community_confirmed',
    report_count: 15,
    source_name: 'Community Report',
    source_logo: 'https://picsum.photos/seed/gas1/100/100',
  },
  {
    id: 'gas-2',
    title: 'Gas Price: $1.89/L at Shell',
    description: 'Shell on 17th Ave SW is at $1.89/L. Prices jumped 5 cents since this morning.',
    category: 'gas',
    neighborhood: 'Beltline',
    lat: 51.037,
    lng: -114.095,
    timestamp: Date.now() - 1000 * 60 * 25, // 25 mins ago
    email: 'beltline_driver@example.com',
    name: 'Marco S.',
    verified_status: 'multiple_reports',
    report_count: 4,
    source_name: 'Community Report',
    source_logo: 'https://picsum.photos/seed/gas2/100/100',
  },
  {
    id: 'gas-3',
    title: 'Gas Price: $1.85/L at Petro-Canada',
    description: 'Petro-Canada on MacLeod Trail reporting $1.85/L. Car wash is also busy.',
    category: 'gas',
    neighborhood: 'Mission',
    lat: 51.012,
    lng: -114.070,
    timestamp: Date.now() - 1000 * 60 * 40, // 40 mins ago
    email: 'macleod_commuter@example.com',
    name: 'Sarah J.',
    verified_status: 'community_confirmed',
    report_count: 7,
    source_name: 'Community Report',
    source_logo: 'https://picsum.photos/seed/gas3/100/100',
  },
  {
    id: 'gas-4',
    title: 'Gas Price: $1.87/L at Esso',
    description: 'Esso on Crowchild Trail is at $1.87/L. Regular fuel only, premium is out of stock.',
    category: 'gas',
    neighborhood: 'Bowness',
    lat: 51.075,
    lng: -114.125,
    timestamp: Date.now() - 1000 * 60 * 55, // 55 mins ago
    email: 'crowchild_user@example.com',
    name: 'Kevin D.',
    verified_status: 'multiple_reports',
    report_count: 3,
    source_name: 'Community Report',
    source_logo: 'https://picsum.photos/seed/gas4/100/100',
  },
];

export const MOCK_COMMUNITY_STATS: CommunityStats[] = [
  {
    community: 'Beltline',
    month: 'March 2024',
    violent_crime: 12,
    property_crime: 45,
    disorder_calls: 78,
    safety_score: 68,
  },
  {
    community: 'Kensington',
    month: 'March 2024',
    violent_crime: 4,
    property_crime: 22,
    disorder_calls: 34,
    safety_score: 82,
  },
  {
    community: 'Bridgeland',
    month: 'March 2024',
    violent_crime: 6,
    property_crime: 28,
    disorder_calls: 41,
    safety_score: 79,
  },
  {
    community: 'Mission',
    month: 'March 2024',
    violent_crime: 5,
    property_crime: 31,
    disorder_calls: 45,
    safety_score: 75,
  },
  {
    community: 'Inglewood',
    month: 'March 2024',
    violent_crime: 7,
    property_crime: 35,
    disorder_calls: 52,
    safety_score: 72,
  },
  {
    community: 'Bowness',
    month: 'March 2024',
    violent_crime: 3,
    property_crime: 18,
    disorder_calls: 25,
    safety_score: 88,
  },
  {
    community: 'Downtown',
    month: 'March 2024',
    violent_crime: 15,
    property_crime: 55,
    disorder_calls: 92,
    safety_score: 62,
  },
];

export function getAreaIntelligence(communityName: string): AreaIntelligence {
  const months = ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'];
  const baseStats = MOCK_COMMUNITY_STATS.find(s => s.community === communityName) || MOCK_COMMUNITY_STATS[0];

  return {
    communityName,
    safetyScore: baseStats.safety_score,
    description: `${communityName} is a ${baseStats.safety_score > 75 ? 'vibrant and safe' : 'dynamic'} neighborhood in Calgary. Recent data shows a ${baseStats.safety_score > 75 ? 'low' : 'moderate'} rate of incidents compared to the city average.`,
    activeIncidents: Math.floor(Math.random() * 5 + 1),
    trend: baseStats.safety_score > 75 ? 'improving' : 'stable',
    monthlyTrends: months.map((month, idx) => ({
      month,
      violent_crime: Math.max(0, baseStats.violent_crime + Math.floor(Math.random() * 6 - 3)),
      property_crime: Math.max(0, baseStats.property_crime + Math.floor(Math.random() * 10 - 5)),
      disorder_calls: Math.max(0, baseStats.disorder_calls + Math.floor(Math.random() * 20 - 10)),
    })),
    insights: [
      `↑ ${Math.floor(Math.random() * 15 + 5)}% increase in property crime in ${communityName} this month`,
      `Safety score of ${baseStats.safety_score} is ${baseStats.safety_score > 75 ? 'above' : 'near'} the city average`,
      'Consistent with historical trends for this season',
      communityName === 'Beltline' || communityName === 'Downtown' ? 'High density area with frequent disorder calls' : 'Residential area with lower incident density',
    ],
    liveOverlayInsight: '3 live reports in last 2 hours (unusual activity for this time of day).',
  };
}
