import { AlertCircle, Car, Construction, CloudRain, ShieldCheck, ShieldAlert, ShieldQuestion, Siren, Clock } from 'lucide-react';
import { INCIDENT_CATEGORY_VALUES } from '@/src/constants';

// Derived from the single source of truth so a new category cannot be added
// to the UI list without the type, the form enum, and the rules contract
// test all seeing it. See src/constants/index.ts.
export type IncidentCategory = (typeof INCIDENT_CATEGORY_VALUES)[number];

export type CredibilityStatus = 'unverified' | 'multiple_reports' | 'community_confirmed' | 'pending_review';

/**
 * data_source distinguishes who created the incident:
 *  - 'community'  Regular user-submitted report (default)
 *  - 'official'   Ingested from a government / authoritative API
 *  - 'system'     Auto-generated by our ingestion pipeline
 *  - 'demo'       Illustrative sample showing how reporting works. Presented
 *                 in the public feed as an anonymous community-style report,
 *                 disclosed in report details, labelled clearly in admin, and
 *                 excluded from every count, score and email.
 */
export type DataSource = 'community' | 'official' | 'system' | 'demo';

/** True when an incident is an illustrative sample rather than a real report. */
export function isDemoIncident(incident: Pick<Incident, 'data_source'>): boolean {
  return incident.data_source === 'demo';
}

/** Public community tabs include illustrative anonymous examples. */
export function isCommunityFacingIncident(incident: Pick<Incident, 'data_source'>): boolean {
  return !incident.data_source || incident.data_source === 'community' || incident.data_source === 'demo';
}

/**
 * Granular tag for the exact data origin — used for dedup and attribution.
 */
export type SourceType =
  | 'user_report'
  | 'env_canada_weather'
  | '511_alberta_traffic'
  | 'calgary_open_data'
  | 'calgary_water_main_breaks'
  | 'alberta_emergency_alert'
  | 'reddit_calgary'
  | 'news_rss'
  | 'calgary_police_crime'
  | 'calgary_infrastructure'
  | 'edmonton_open_data'
  | 'alberta_statcan_crime'
  | 'enmax_power_outage';

// Typed as a total Record so adding a category to INCIDENT_CATEGORIES fails
// the typecheck here until an icon is supplied.
export const CATEGORY_ICONS: Record<IncidentCategory, typeof AlertCircle> = {
  crime: AlertCircle,
  traffic: Car,
  infrastructure: Construction,
  weather: CloudRain,
  emergency: Siren,
};

export const STATUS_ICONS = {
  unverified: ShieldQuestion,
  multiple_reports: ShieldAlert,
  community_confirmed: ShieldCheck,
  pending_review: Clock,
};

/**
 * Public visibility of an incident, and the single field the map query filters
 * on.
 *
 * Replaces the old `flagged` / `deleted` boolean pair. Two booleans allowed
 * four states for three meanings, needed two indexes, and could not be
 * expressed as one query constraint — which meant takedown could only ever be
 * enforced in the client. One field gives Firestore rules something to
 * validate and the map one `where()` clause.
 */
export type IncidentVisibility = 'public' | 'flagged' | 'deleted';

/** Distinct flags required before a community report is hidden from the map. */
export const FLAG_THRESHOLD = 2;

export interface Incident {
  id: string;
  title: string;
  description: string;
  category: IncidentCategory;
  neighborhood: string;
  lat: number;
  lng: number;
  timestamp: number;
  /**
   * Present only on ingested/system records, where it is a synthetic service
   * address. Reporter email for community reports lives in the admin-only
   * `incident_reporters/{incidentId}` document and is never published here.
   */
  email?: string;
  name: string;
  anonymous?: boolean;
  verified_status: CredibilityStatus;
  image_url?: string;
  report_count: number;
  source_url?: string;
  source_logo?: string;
  source_name?: string;
  /**
   * Authoritative visibility. Absent on documents written before the
   * visibility migration — treat a missing value as 'public'.
   */
  visibility?: IncidentVisibility;
  /** Distinct users who have flagged this report; length drives the takedown. */
  flagged_by?: string[];
  flag_count?: number;
  flagged_at?: number;
  deletedAt?: number;
  deletedBy?: string;
  /** @deprecated Superseded by `visibility`. Retained for old documents. */
  deleted?: boolean;
  /** @deprecated Superseded by `visibility`. Retained for old documents. */
  flagged?: boolean;
  authorUid?: string;
  // ── Provenance fields (set by ingestion pipeline or client) ──────────────
  /** Who created this record. Defaults to 'community' when absent. */
  data_source?: DataSource;
  /** Specific origin of the data, used for deduplication. */
  source_type?: SourceType;
  /**
   * Stable identifier for deduplication: `<source_type>:<external_id>`.
   * The ingestion script checks this field before writing to avoid duplicates.
   */
  dedup_key?: string;
  /**
   * Unix ms after which this incident should be hidden client-side.
   * Ingestion sets this; undefined = never expires (user reports).
   */
  expires_at?: number;
  /** Precision of the displayed pin; demo reports use neighbourhood anchors. */
  location_precision?: 'exact' | 'neighborhood';
}

export interface CommunityStats {
  community: string;
  month: string;
  violent_crime: number;
  property_crime: number;
  disorder_calls: number;
  safety_score: number;
}

export interface AreaIntelligence {
  communityName: string;
  crimeKey?: string;        // stats map lookup key (e.g. "edmonton:downtown"); defaults to communityName.toLowerCase()
  safetyScore: number;
  description: string;
  activeIncidents: number;
  trend: 'improving' | 'declining' | 'stable';
  monthlyTrends: {
    month: string;
    violent_crime: number;
    property_crime: number;
    disorder_calls: number;
  }[];
  insights: string[];
  liveOverlayInsight: string;
}

/**
 * Private reporter metadata, split out of the public incident document.
 *
 * `incidents` is world-readable so the map works signed-out; anything that
 * identifies the reporter has to live somewhere else. Written in the same
 * batch as the incident so the two can never diverge.
 */
export interface IncidentReporter {
  incidentId: string;
  authorUid: string;
  email: string;
  createdAt: number;
}

/** Resolves visibility for documents written before the migration. */
export function incidentVisibility(
  incident: Pick<Incident, 'visibility' | 'deleted' | 'flagged'>,
): IncidentVisibility {
  if (incident.visibility) return incident.visibility;
  if (incident.deleted) return 'deleted';
  if (incident.flagged) return 'flagged';
  return 'public';
}

/** True when an incident should appear on the public map and feed. */
export function isPubliclyVisible(
  incident: Pick<Incident, 'visibility' | 'deleted' | 'flagged'>,
): boolean {
  return incidentVisibility(incident) === 'public';
}
