import { AlertCircle, Car, Construction, CloudRain, ShieldCheck, ShieldAlert, ShieldQuestion, Siren, Clock } from 'lucide-react';

export type IncidentCategory = 'crime' | 'traffic' | 'infrastructure' | 'weather' | 'emergency';

export type CredibilityStatus = 'unverified' | 'multiple_reports' | 'community_confirmed' | 'pending_review';

/**
 * data_source distinguishes who created the incident:
 *  - 'community'  Regular user-submitted report (default)
 *  - 'official'   Ingested from a government / authoritative API
 *  - 'system'     Auto-generated by our ingestion pipeline
 */
export type DataSource = 'community' | 'official' | 'system';

/**
 * Granular tag for the exact data origin — used for dedup and attribution.
 */
export type SourceType =
  | 'user_report'
  | 'env_canada_weather'
  | '511_alberta_traffic'
  | 'calgary_open_data';

export const CATEGORY_ICONS = {
  crime: AlertCircle,
  traffic: Car,
  infrastructure: Construction,
  weather: CloudRain,
  emergency: Siren,
};

export const STATUS_ICONS = {
  unverified: ShieldQuestion,
  multiple_reports: ShieldAlert,
  community_confirmed: ShieldCheck,
  pending_review: Clock,
};

export interface Incident {
  id: string;
  title: string;
  description: string;
  category: IncidentCategory;
  neighborhood: string;
  lat: number;
  lng: number;
  timestamp: number;
  email: string;
  name: string;
  anonymous?: boolean;
  verified_status: CredibilityStatus;
  image_url?: string;
  report_count: number;
  source_url?: string;
  source_logo?: string;
  source_name?: string;
  deleted?: boolean;
  deletedAt?: number;
  deletedBy?: string;
  // ── Provenance fields (set by ingestion pipeline or client) ──────────────
  /** Who created this record. Defaults to 'community' when absent. */
  data_source?: DataSource;
  /** Specific origin of the data, used for deduplication. */
  source_type?: SourceType;
  /**
   * Stable identifier for deduplication: `<source_type>:<external_id>`.
   * The ingestion script checks this field before writing to avoid duplicates.
   */
  dedup_key?: string;
  /**
   * Unix ms after which this incident should be hidden client-side.
   * Ingestion sets this; undefined = never expires (user reports).
   */
  expires_at?: number;
}

export interface CommunityStats {
  community: string;
  month: string;
  violent_crime: number;
  property_crime: number;
  disorder_calls: number;
  safety_score: number;
}

export interface AreaIntelligence {
  communityName: string;
  safetyScore: number;
  description: string;
  activeIncidents: number;
  trend: 'improving' | 'declining' | 'stable';
  monthlyTrends: {
    month: string;
    violent_crime: number;
    property_crime: number;
    disorder_calls: number;
  }[];
  insights: string[];
  liveOverlayInsight: string;
}
